apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kubernetes-test-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
spec:
  storageClassName: local
  resources:
    requests:
      storage: 9Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: wp-pv
